export interface FaqItem {
  question: string;
  answer: string;
}

export const genelFaqs: FaqItem[] = [
  { question: "OJS Nutrition ürünlerinin menşei neresi?", answer: "Ürünlerimiz, en yüksek kalite standartlarına uygun olarak Avrupa'da üretilmekte ve Türkiye'de paketlenmektedir. Hammaddelerimiz dünyanın önde gelen tedarikçilerinden temin edilmektedir." },
  { question: "Hangi sertifikalarınız var?", answer: "Tüm ürünlerimiz GMP (İyi Üretim Uygulamaları), ISO 22000 ve Helal sertifikalarına sahiptir. Sağlık ve güvenliğiniz bizim için en önemli önceliktir." },
  { question: "Satılan ürünler garantili midir? Değişim var mı?", answer: "Ambalajı açılmamış ve hasar görmemiş tüm ürünlerimizde 14 gün içinde iade ve değişim garantisi sunuyoruz. Detaylı bilgi için İade ve Değişim politikamızı inceleyebilirsiniz." },
  { question: "Sipariş verirken sorun yaşıyorum, ne yapmam gerekir?", answer: "Sipariş sırasında herhangi bir sorunla karşılaşırsanız, canlı destek hattımızdan veya 'İletişim' sayfamızdaki bilgilerden bize ulaşabilirsiniz. Müşteri hizmetleri ekibimiz size yardımcı olmaktan mutluluk duyacaktır." },
  { question: "OJS Nutrition ürünleri nerede satılıyor?", answer: "Ürünlerimizi resmi web sitemiz ojsnutrition.com üzerinden ve seçkin yetkili bayilerimiz aracılığıyla satın alabilirsiniz." },
  { question: "Yüksek proteinli ürünleri kimler kullanabilir?", answer: "Yüksek proteinli ürünlerimiz, sporcular, aktif bir yaşam tarzına sahip olanlar ve günlük protein alımını artırmak isteyen herkes için uygundur. Herhangi bir sağlık sorununuz varsa kullanmadan önce doktorunuza danışmanızı öneririz." },
  { question: "Ürünlerinizde domuz yağı veya katkıları bulunuyor mu?", answer: "Hayır, ürünlerimizin hiçbirinde domuz yağı veya domuzdan elde edilmiş herhangi bir katkı maddesi bulunmamaktadır. Helal sertifikamız bu konudaki hassasiyetimizin bir göstergesidir." },
  { question: "Ürünlerin son kullanma tarihleri nerede yazıyor?", answer: "Tüm ürünlerimizin son kullanma tarihi (SKT) ve parti numarası, ambalajın altında veya kapağında açıkça belirtilmiştir." },
  { question: "Toplu alımlarda indirim yapıyor musunuz?", answer: "Evet, spor salonları, diyetisyenler ve kurumsal müşterilerimiz için özel toptan alım koşulları ve indirimler sunuyoruz. Detaylar için lütfen bizimle iletişime geçin." },
  { question: "Üyelik oluşturmanın avantajları nelerdir?", answer: "Üye olarak siparişlerinizi daha hızlı verebilir, geçmiş siparişlerinizi görüntüleyebilir, size özel kampanya ve indirimlerden ilk siz haberdar olabilirsiniz." },
  { question: "Şifremi unuttum, ne yapmalıyım?", answer: "Giriş sayfasındaki 'Şifremi Unuttum' bağlantısına tıklayarak e-posta adresinize yeni bir şifre belirleme bağlantısı gönderebilirsiniz." },
  { question: "Ürünleriniz vejetaryen/veganlar için uygun mu?", answer: "Bazı ürünlerimiz (örneğin bitkisel proteinler) vegan ve vejetaryenler için uygundur. Ürün açıklamalarında ve etiketlerinde bu bilgi açıkça belirtilmiştir. Whey protein gibi süt bazlı ürünlerimiz vejetaryenler için uygunken, veganlar için uygun değildir." },
  { question: "Taksit seçeneği neden yok?", answer: "Şu anki ödeme altyapımızda taksit seçeneği bulunmamaktadır. Müşterilerimize en uygun fiyatları sunabilmek adına operasyonel maliyetlerimizi minimumda tutmaya çalışıyoruz. Gelecekte bu seçeneği eklemek için çalışmalarımız devam etmektedir." },
  { question: "Sattığınız ürünler ilaç mıdır?", answer: "Hayır, sattığımız ürünlerin hiçbiri ilaç değildir. Ürünlerimiz, Tarım ve Orman Bakanlığı onaylı gıda takviyeleridir ve hastalıkları teşhis veya tedavi etme amacı taşımazlar." },
];

export const urunlerFaqs: FaqItem[] = [
    { question: "Whey protein ile izole protein arasındaki fark nedir?", answer: "İzole protein, daha yüksek protein oranına ve daha düşük laktoz/yağ oranına sahip olacak şekilde daha fazla işlemden geçer. Laktoz intoleransı olanlar veya daha saf bir protein kaynağı arayanlar için idealdir. Whey konsantresi ise başlangıç seviyesi için harika bir seçenektir." },
    { question: "Pre-workout ürünlerini ne zaman kullanmalıyım?", answer: "Pre-workout (antrenman öncesi) ürünleri, antrenmandan yaklaşık 20-30 dakika önce kullanılmalıdır. Bu, ürünün içeriğindeki aktif bileşenlerin kan dolaşımınıza karışması ve antrenman sırasında maksimum faydayı sağlamanız için yeterli bir süredir." },
    { question: "Kreatin kullanımı su tutar mı?", answer: "Kreatin, kas hücrelerinin içinde su tutarak kasların daha dolgun görünmesini sağlar ve performansı artırır. Bu durum, deri altında su toplanması gibi bir ödem değildir ve kreatin döngüsü bittiğinde normale döner." },
    { question: "BCAA ve EAA arasındaki temel fark nedir?", answer: "BCAA (Dallı Zincirli Amino Asitler) 3 temel amino asiti içerirken, EAA (Esansiyel Amino Asitler) vücudun üretemediği 9 temel amino asitin tümünü içerir. EAA, kas protein sentezi için daha kapsamlı bir destek sunar." },
    { question: "Gainer (kilo aldırıcı) ürünleri kimler için uygundur?", answer: "Gainer ürünleri, kilo almakta veya kas kütlesini artırmakta zorlanan, yüksek kalori ihtiyacı olan kişiler (ektomorf vücut tipleri) için tasarlanmıştır. Normalde yeterli kalori alamayanlar için pratik bir alternatiftir." },
    { question: "Vitamin takviyelerini aç mı tok mu almalıyım?", answer: "Yağda çözünen vitaminler (A, D, E, K) genellikle yemeklerle birlikte alındığında daha iyi emilir. Suda çözünen vitaminler (C ve B kompleks) ise günün herhangi bir saatinde alınabilir. En doğru bilgi için ürün etiketini kontrol ediniz." },
    { question: "Protein barlar öğün yerine geçer mi?", answer: "Protein barlar, yoğun zamanlarda pratik bir atıştırmalık veya ara öğün seçeneğidir. Ancak tam bir öğünün besin çeşitliliğini ve doyuruculuğunu sağlamazlar. Dengeli bir diyetin parçası olarak tüketilmelidirler." },
    { question: "L-Karnitin ve CLA birlikte kullanılabilir mi?", answer: "Evet, L-Karnitin ve CLA, yağ metabolizmasını destekleyen farklı mekanizmalar üzerinden çalıştıkları için sıklıkla birlikte kullanılırlar ve sinerjik bir etki yaratabilirler." },
    { question: "Ürünlerinizi nasıl saklamalıyım?", answer: "Ürünlerinizi doğrudan güneş ışığından uzak, serin ve kuru bir yerde saklamanız önerilir. Özellikle protein tozlarının nem almamasına dikkat ediniz." },
    { question: "Aroma seçimi performansı etkiler mi?", answer: "Hayır, aroma seçimi ürünün besin değerlerini veya performans üzerindeki etkisini değiştirmez. Tamamen kişisel damak zevkinize göre seçim yapabilirsiniz." },
    { question: "Hamilelik veya emzirme döneminde ürünlerinizi kullanabilir miyim?", answer: "Hamilelik ve emzirme gibi hassas dönemlerde herhangi bir gıda takviyesi kullanmadan önce mutlaka doktorunuza veya bir sağlık uzmanına danışmanız gerekmektedir." },
    { question: "Çocuklar gıda takviyesi kullanabilir mi?", answer: "Gıda takviyeleri genellikle yetişkinlerin ihtiyaçlarına yönelik formüle edilmiştir. Çocukların kullanımı için mutlaka bir çocuk doktoruna danışılmalıdır." },
    { question: "Antrenman yapmadığım günler de protein tozu kullanmalı mıyım?", answer: "Evet, kas onarımı ve gelişimi dinlenme günlerinde de devam eder. Antrenman yapmadığınız günlerde de günlük protein hedefinize ulaşmak için protein tozu kullanabilirsiniz." },
    { question: "Kapağın altındaki folyo açılmış veya tam yapışmamış gibi duruyor?", answer: "Üretim sürecinde basınçla yapıştırılan folyolar, bazen kapak açılırken kapağa yapışıp kalabilir. Bu durum ürünün hava aldığı anlamına gelmez. Eğer folyo tamamen yerinden çıkmış veya yırtıksa, lütfen müşteri hizmetlerimizle iletişime geçin." },
];

export const kargoFaqs: FaqItem[] = [
    { question: "Siparişim ne zaman kargoya verilir?", answer: "Hafta içi saat 16:00'a kadar verilen siparişler aynı gün kargoya verilir. 16:00'dan sonra ve hafta sonu verilen siparişler ise bir sonraki iş günü kargoya teslim edilir." },
    { question: "Hangi kargo firması ile çalışıyorsunuz?", answer: "Siparişlerinizi Türkiye'nin her yerine Yurtiçi Kargo ve MNG Kargo güvencesiyle gönderiyoruz. Sipariş ekranında kargo firmanızı seçebilirsiniz." },
    { question: "Kargo ücreti ne kadar?", answer: "500 TL ve üzeri tüm siparişlerinizde kargo ücretsizdir. Bu tutarın altındaki siparişler için standart kargo ücreti uygulanmaktadır." },
    { question: "Siparişimin durumunu nasıl takip edebilirim?", answer: "Siparişiniz kargoya verildiğinde size bir SMS ve e-posta ile takip numarası gönderilecektir. Bu numara ile ilgili kargo firmasının web sitesinden siparişinizin durumunu anlık olarak takip edebilirsiniz." },
    { question: "Kargom hasarlı geldi, ne yapmalıyım?", answer: "Kargonuzu teslim alırken kargo görevlisinin yanında paketi kontrol etmenizi rica ederiz. Herhangi bir hasar, ezilme veya yırtık durumunda kargo görevlisine 'Hasar Tespit Tutanağı' tutturarak ürünü teslim almayınız ve bizimle iletişime geçiniz." },
    { question: "Kapıda ödeme seçeneğiniz var mı?", answer: "Evet, kapıda nakit veya kredi kartı ile ödeme seçeneğimiz mevcuttur. Kapıda ödeme seçeneği, standart kargo ücretine ek olarak küçük bir hizmet bedeli içerebilir." },
    { question: "Teslimat adresimi değiştirebilir miyim?", answer: "Siparişiniz 'Hazırlanıyor' statüsündeyken, yani henüz kargoya verilmemişken müşteri hizmetlerimizle iletişime geçerek adres değişikliği yapabilirsiniz. Kargoya verilen siparişlerde adres değişikliği yapılamamaktadır." },
    { question: "Resmi tatillerde teslimat yapılıyor mu?", answer: "Kargo firmaları resmi tatil günlerinde çalışmadığı için bu günlerde teslimat yapılamamaktadır. Siparişiniz resmi tatili takip eden ilk iş gününde işleme alınacaktır." },
    { question: "Kargom belirtilen sürede gelmedi, ne yapmalıyım?", answer: "Kargo takip numaranız ile kargo firmasının sitesinden durumu kontrol edebilirsiniz. Eğer 'Teslim Edilemedi' veya benzeri bir not varsa, şubeyle iletişime geçmeniz gerekebilir. Gecikme devam ederse, lütfen bizimle iletişime geçin, süreci sizin için takip edelim." },
    { question: "Yurt dışına gönderim yapıyor musunuz?", answer: "Hayır, şu an için sadece Türkiye sınırları içerisine gönderim yapmaktayız." },
    { question: "Siparişimi şubeden teslim alabilir miyim?", answer: "Sipariş verirken teslimat adresi olarak bir adres belirtmeniz gerekmektedir. Ancak kargonuz yola çıktıktan sonra kargo firmasıyla iletişime geçerek veya mobil uygulamaları üzerinden 'Şubeden Teslim Al' seçeneğini kullanmayı deneyebilirsiniz." },
    { question: "İptal ve İade ettiğim ürünlerin tutarı hesabıma ne zaman aktarılır?", answer: "İade ettiğiniz ürün depomuza ulaşıp kontrolleri yapıldıktan sonra 2-3 iş günü içerisinde iade işleminiz onaylanır. Bankanıza bağlı olarak, iade tutarının hesabınıza veya kartınıza yansıması 3 ila 10 iş gününü bulabilir." },
    { question: "Siparişimi teslim alırken nelere dikkat etmeliyim?", answer: "Kargo poşetinin veya kolisinin hasarsız olduğundan emin olun. Hasarlı bir paketle karşılaşırsanız, kargo görevlisine tutanak tutturup paketi kabul etmeme hakkınız bulunmaktadır." },
    { question: "Sipariş takibimi nasıl yapabilirim?", answer: "Hesabım > Siparişlerim bölümünden veya size gönderilen kargo takip linkinden siparişinizin tüm hareketlerini kolayca takip edebilirsiniz." },
];